%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/lfast_shared/SlewDriveTestLogs/SinTests/digital.csv
%
% Auto-generated by MATLAB on 17-Mar-2023 14:19:26
clc; close all; clear;

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter*1000
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Times", "CHA", "CHB"];
opts.VariableTypes = ["double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["CHA", "CHB"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["CHA", "CHB"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("/home/lfast_shared/SlewDriveTestLogs/Mixed/mixed_0.csv", opts);

%% Convert to output type
time = tbl.Times;
CHA = tbl.CHA;
CHB = tbl.CHB;
N = numel(time);
%% Clear temporary variables
clear opts tbl


%% and go.
quadStates = bin2dec(strcat(CHA, CHB));

state = quadStates(1);
prevState = quadStates(1);
counts = zeros(1,N);

for ii = 2:N
    state = quadStates(ii);
    if state == 0
        if prevState == 2
            dc = 1;
        elseif prevState == 1
            dc = -1;
        else
            dc = NaN;
        end
    elseif state == 1
        if prevState == 0
            dc = 1;
        elseif prevState == 3
            dc = -1;
        else
            dc = NaN;
        end
    elseif state == 3
        if prevState == 1
            dc = 1;
        elseif prevState == 2
            dc = -1;
        else
            dc = NaN;
        end
    elseif state == 2
        if prevState == 3
            dc = 1;
        elseif prevState == 0
            dc = -1;
        else
            dc = NaN;
        end
    end

    if ~isnan(dc)
        counts(ii) = counts(ii - 1) + dc;
    else
        counts(ii) = dc;
    end
    prevState = state;
end

tiledlayout(2,1);
nexttile;
plot(time, counts, '.-')
nexttile;
plot(time(1:end-1), diff(counts)./diff(time))
