%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/lfast_shared/SlewDriveTestLogs/TRQ_2023_02_27_14_06_35.csv
%
% Auto-generated by MATLAB on 27-Feb-2023 14:07:55
clc; close all; clear;
%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["dt_uS", "CMDA", "CMDB", "CURA", "CURB", "VELA", "VELB", "POSA", "POSB"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data

folder = "/home/lfast_shared/SlewDriveTestLogs/2023_05_04/";

% fileName = "SDR_FRCTN_2023_04_26_13_13_18_EL";
% fileName = "SDR_FRCTN_2023_04_26_12_25_52_AZ";
% fileName = "SDR_FRCTN_2023_04_26_15_35_26_AZ";
% fileName = "SDR_FRCTN_2023_04_26_15_29_16_EL2";

% fileName = 'JSSG_2006_2023_05_03_09_30_02';
fileName = 'TRQ_2023_05_04_15_07_03';
fp = fullfile(folder, strcat(fileName, ".csv"));

tbl = readtable(fp, opts);

%% Convert to output type
dt_uS = tbl.dt_uS;
CMDA = tbl.CMDA;
CMDB = tbl.CMDB;
CURA = tbl.CURA;
CURB = tbl.CURB;
VELA = tbl.VELA;
VELB = tbl.VELB;
POSA = tbl.POSA;
POSB = tbl.POSB;

%% Clear temporary variables
clear opts tbl

% figure(99);
% subplot(2,1,1)
% plot(VELA)
% title("Velocity A")
% hold on
% plot(CMDA)
% subplot(2,1,2)
% plot(CURB)
% title("Torque B")
% hold on
% plot(CMDB)
% 
% 
f98 = figure(98);
f98.Position = [1578 883 550 427];
tiledlayout(2,1);
nexttile;
plot(POSA)
title("Posn A")
nexttile;
plot(POSB)
title("Posn B")

f95 = figure(95);
f95.Position =[422 896 570 413];
tiledlayout(2,1)
nexttile;
plot(CURA)
hold on;
plot(CMDA)
legend("Curr A", "Command A")
nexttile;
plot(CURB)
hold on;
plot(CMDB)
legend("Curr B", "Command B")
grid on


f97 = figure(97);
f97.Position = [995 909 570 413];
tiledlayout(2,1)
nexttile;
plot(VELA)
title("VEL A")

nexttile;
plot(VELB)
title("VEL B")


f88 = figure(88);
f88.Position = [151 384 570 413];
CUR = (CURA + CURB);
VEL = (VELA+VELB)/2;
POS = (POSA + POSB)/2;
% plot(VEL, CUR)
plot(POSA, CURA, '.');
hold on
plot(POSB, CURB, '.');

grid on;
